on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

name: Ingetration Test on TDX Server

env:
  AS: nasm
  AR_x86_64_unknown_uefi: llvm-ar
  CC_x86_64_unknown_uefi: clang
  RUST_TOOLCHAIN: nightly-2021-08-20
  TOOLCHAIN_PROFILE: minimal

jobs:
  system_compile:
    name: Run Integration Test on TDX Server
    runs-on: [self-hosted, tdx]
    timeout-minutes: 30

    steps:
      # Install first since it's needed to build NASM
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: ${{ env.TOOLCHAIN_PROFILE }}
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
          components: rust-src, llvm-tools-preview

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Run cargo install cargo-xbuild
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-xbuild

      # install QEMU
      - name: Install QEMU (Linux)
        run: sudo dnf install qemu-kvm -y
      - name: "Print QEMU Version"
        run: qemu-system-x86_64 --version

      - name: Change lock_api to 0.4.6
        run: |
          sed -i 's/version = "0.4.7"/version = "0.4.6"/' Cargo.lock
          sed -i 's/327fa5b6a6940e4699ec49a9beae1ea4845c6bab9314e4f84ac68742139d8c53/88943dd7ef4a2e5a4bfa2753aaab3013e34ce2533d1996fb18ef591e315e2b3b/' Cargo.lock

      - name: Run Tests
        run: make integration-test
